// Generated by scripts/generate-client-config.js — edit .env / Vercel env vars instead
window.INDEX0_CONFIG = {
  "apiBase": "",
  "backendUrl": "https://index0-backend.onrender.com"
};

(function resolveApiBase() {
  const cfg = window.INDEX0_CONFIG || {};

  if (typeof cfg.apiBase === 'string') {
    window.INDEX0_API_BASE = cfg.apiBase.trim();
  } else if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    window.INDEX0_API_BASE = 'http://localhost:3000';
  } else if (typeof cfg.backendUrl === 'string' && cfg.backendUrl.trim() !== '') {
    window.INDEX0_API_BASE = cfg.backendUrl.trim().replace(/\/$/, '');
  } else {
    window.INDEX0_API_BASE = '';
  }
})();
